# Generated by Django 5.2 on 2025-05-12 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_homemoney'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeMoney',
        ),
    ]
