# Generated by Django 5.2 on 2025-05-12 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_delete_homemoney'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_money',
            fields=[
                ('money_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('money', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('money_comment', models.CharField(blank=True, max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
