# Generated by Django 5.2 on 2025-05-15 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='home_money',
            fields=[
                ('money_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('money', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('money_comment', models.CharField(blank=True, max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
