# Generated by Django 5.2 on 2025-06-19 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home_money',
            old_name='user_id',
            new_name='user',
        ),
    ]
