# Generated by Django 5.2 on 2025-06-19 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_manager', '0002_rename_user_id_home_money_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home_money',
            old_name='user',
            new_name='user_id',
        ),
    ]
